/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.yakindu.analysis.example;

import hu.bme.mit.yakindu.analysis.IStatemachine;
import hu.bme.mit.yakindu.analysis.ITimerCallback;

public interface IExampleStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseStart();
		
		public void raiseWhite();
		
		public void raiseWhite2();
		
		public void raiseGray();
		
		public void raiseNotgray();
		
		public long getWhiteTime();
		
		public void setWhiteTime(long value);
		
		public long getWhite2Time();
		
		public void setWhite2Time(long value);
		
	}
	
	public SCInterface getSCInterface();
	
}
